name: Tox

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tox Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.11, 3.10, 3.9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6
      - run: uvx --with tox-uv tox -e ${{ matrix.python-version }}

  type-check:
    name: Tox Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: astral-sh/setup-uv@v6
      - run: uvx --with tox-uv tox -e type
